import { Inter } from "next/font/google";
import "./globals.css";
import Heeader from "/app/Heeader";
import Footer from "./Footer";
import ClientContent from "./ClientContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "جهاد دانشگاهی",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0", 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-200 ${inter.className}`}>
        <ClientContent>
          <Heeader /> 
          {children}
          <Footer />
        </ClientContent>
      </body>
    </html>
  );
}
